// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// FollowHandler is an autogenerated mock type for the FollowHandler type
type FollowHandler struct {
	mock.Mock
}

// Follow provides a mock function with given fields:
func (_m *FollowHandler) Follow() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// ShowAllFollower provides a mock function with given fields:
func (_m *FollowHandler) ShowAllFollower() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// ShowAllFollowing provides a mock function with given fields:
func (_m *FollowHandler) ShowAllFollowing() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// Unfollow provides a mock function with given fields:
func (_m *FollowHandler) Unfollow() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

type mockConstructorTestingTNewFollowHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewFollowHandler creates a new instance of FollowHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFollowHandler(t mockConstructorTestingTNewFollowHandler) *FollowHandler {
	mock := &FollowHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
