// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// ImageDelivery_ is an autogenerated mock type for the ImageDelivery_ type
type ImageDelivery_ struct {
	mock.Mock
}

// DeleteImageById provides a mock function with given fields: e
func (_m *ImageDelivery_) DeleteImageById(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteImageByRecipeId provides a mock function with given fields: e
func (_m *ImageDelivery_) DeleteImageByRecipeId(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertImage provides a mock function with given fields: e
func (_m *ImageDelivery_) InsertImage(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateImageById provides a mock function with given fields: e
func (_m *ImageDelivery_) UpdateImageById(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewImageDelivery_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewImageDelivery_ creates a new instance of ImageDelivery_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewImageDelivery_(t mockConstructorTestingTNewImageDelivery_) *ImageDelivery_ {
	mock := &ImageDelivery_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
