// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	images "alta-cookit-be/features/images"

	mock "github.com/stretchr/testify/mock"
)

// ImageService_ is an autogenerated mock type for the ImageService_ type
type ImageService_ struct {
	mock.Mock
}

// DeleteImageById provides a mock function with given fields: imageEntity
func (_m *ImageService_) DeleteImageById(imageEntity *images.ImageEntity) error {
	ret := _m.Called(imageEntity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*images.ImageEntity) error); ok {
		r0 = rf(imageEntity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertImage provides a mock function with given fields: imageEntity
func (_m *ImageService_) InsertImage(imageEntity *[]images.ImageEntity) (*[]images.ImageEntity, error) {
	ret := _m.Called(imageEntity)

	var r0 *[]images.ImageEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*[]images.ImageEntity) (*[]images.ImageEntity, error)); ok {
		return rf(imageEntity)
	}
	if rf, ok := ret.Get(0).(func(*[]images.ImageEntity) *[]images.ImageEntity); ok {
		r0 = rf(imageEntity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]images.ImageEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*[]images.ImageEntity) error); ok {
		r1 = rf(imageEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateImageById provides a mock function with given fields: imageEntity
func (_m *ImageService_) UpdateImageById(imageEntity *images.ImageEntity) (*images.ImageEntity, error) {
	ret := _m.Called(imageEntity)

	var r0 *images.ImageEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*images.ImageEntity) (*images.ImageEntity, error)); ok {
		return rf(imageEntity)
	}
	if rf, ok := ret.Get(0).(func(*images.ImageEntity) *images.ImageEntity); ok {
		r0 = rf(imageEntity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*images.ImageEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*images.ImageEntity) error); ok {
		r1 = rf(imageEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewImageService_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewImageService_ creates a new instance of ImageService_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewImageService_(t mockConstructorTestingTNewImageService_) *ImageService_ {
	mock := &ImageService_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
