// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// IngredientDetailDelivery_ is an autogenerated mock type for the IngredientDetailDelivery_ type
type IngredientDetailDelivery_ struct {
	mock.Mock
}

// DeleteIngredientDetailById provides a mock function with given fields: e
func (_m *IngredientDetailDelivery_) DeleteIngredientDetailById(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertIngredientDetail provides a mock function with given fields: e
func (_m *IngredientDetailDelivery_) InsertIngredientDetail(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateIngredientDetailById provides a mock function with given fields: e
func (_m *IngredientDetailDelivery_) UpdateIngredientDetailById(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIngredientDetailDelivery_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewIngredientDetailDelivery_ creates a new instance of IngredientDetailDelivery_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIngredientDetailDelivery_(t mockConstructorTestingTNewIngredientDetailDelivery_) *IngredientDetailDelivery_ {
	mock := &IngredientDetailDelivery_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
