// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	likes "alta-cookit-be/features/likes"

	mock "github.com/stretchr/testify/mock"
)

// LikeData_ is an autogenerated mock type for the LikeData_ type
type LikeData_ struct {
	mock.Mock
}

// LikeRecipe provides a mock function with given fields: entity
func (_m *LikeData_) LikeRecipe(entity *likes.LikeEntity) error {
	ret := _m.Called(entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*likes.LikeEntity) error); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnlikeRecipe provides a mock function with given fields: entity
func (_m *LikeData_) UnlikeRecipe(entity *likes.LikeEntity) error {
	ret := _m.Called(entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*likes.LikeEntity) error); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewLikeData_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewLikeData_ creates a new instance of LikeData_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLikeData_(t mockConstructorTestingTNewLikeData_) *LikeData_ {
	mock := &LikeData_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
