// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	likes "alta-cookit-be/features/likes"

	mock "github.com/stretchr/testify/mock"
)

// LikeService_ is an autogenerated mock type for the LikeService_ type
type LikeService_ struct {
	mock.Mock
}

// LikeRecipe provides a mock function with given fields: entity
func (_m *LikeService_) LikeRecipe(entity *likes.LikeEntity) error {
	ret := _m.Called(entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*likes.LikeEntity) error); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnlikeRecipe provides a mock function with given fields: entity
func (_m *LikeService_) UnlikeRecipe(entity *likes.LikeEntity) error {
	ret := _m.Called(entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*likes.LikeEntity) error); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewLikeService_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewLikeService_ creates a new instance of LikeService_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLikeService_(t mockConstructorTestingTNewLikeService_) *LikeService_ {
	mock := &LikeService_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
