// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	recipes "alta-cookit-be/features/recipes"

	mock "github.com/stretchr/testify/mock"
)

// RecipeService_ is an autogenerated mock type for the RecipeService_ type
type RecipeService_ struct {
	mock.Mock
}

// DeleteRecipeById provides a mock function with given fields: entity
func (_m *RecipeService_) DeleteRecipeById(entity *recipes.RecipeEntity) error {
	ret := _m.Called(entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*recipes.RecipeEntity) error); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertRecipe provides a mock function with given fields: entity
func (_m *RecipeService_) InsertRecipe(entity *recipes.RecipeEntity) (*recipes.RecipeEntity, error) {
	ret := _m.Called(entity)

	var r0 *recipes.RecipeEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*recipes.RecipeEntity) (*recipes.RecipeEntity, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(*recipes.RecipeEntity) *recipes.RecipeEntity); ok {
		r0 = rf(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recipes.RecipeEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*recipes.RecipeEntity) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectRecipeDetailById provides a mock function with given fields: entity
func (_m *RecipeService_) SelectRecipeDetailById(entity *recipes.RecipeEntity) (*recipes.RecipeEntity, error) {
	ret := _m.Called(entity)

	var r0 *recipes.RecipeEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*recipes.RecipeEntity) (*recipes.RecipeEntity, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(*recipes.RecipeEntity) *recipes.RecipeEntity); ok {
		r0 = rf(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recipes.RecipeEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*recipes.RecipeEntity) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectRecipes provides a mock function with given fields: entity
func (_m *RecipeService_) SelectRecipes(entity *recipes.RecipeEntity) (*[]recipes.RecipeEntity, error) {
	ret := _m.Called(entity)

	var r0 *[]recipes.RecipeEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*recipes.RecipeEntity) (*[]recipes.RecipeEntity, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(*recipes.RecipeEntity) *[]recipes.RecipeEntity); ok {
		r0 = rf(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]recipes.RecipeEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*recipes.RecipeEntity) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectRecipesTimeline provides a mock function with given fields: entity
func (_m *RecipeService_) SelectRecipesTimeline(entity *recipes.RecipeEntity) (*[]recipes.RecipeEntity, error) {
	ret := _m.Called(entity)

	var r0 *[]recipes.RecipeEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*recipes.RecipeEntity) (*[]recipes.RecipeEntity, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(*recipes.RecipeEntity) *[]recipes.RecipeEntity); ok {
		r0 = rf(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]recipes.RecipeEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*recipes.RecipeEntity) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectRecipesTrending provides a mock function with given fields: entity
func (_m *RecipeService_) SelectRecipesTrending(entity *recipes.RecipeEntity) (*[]recipes.RecipeEntity, error) {
	ret := _m.Called(entity)

	var r0 *[]recipes.RecipeEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*recipes.RecipeEntity) (*[]recipes.RecipeEntity, error)); ok {
		return rf(entity)
	}
	if rf, ok := ret.Get(0).(func(*recipes.RecipeEntity) *[]recipes.RecipeEntity); ok {
		r0 = rf(entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]recipes.RecipeEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*recipes.RecipeEntity) error); ok {
		r1 = rf(entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRecipeById provides a mock function with given fields: entity
func (_m *RecipeService_) UpdateRecipeById(entity *recipes.RecipeEntity) error {
	ret := _m.Called(entity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*recipes.RecipeEntity) error); ok {
		r0 = rf(entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRecipeService_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewRecipeService_ creates a new instance of RecipeService_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRecipeService_(t mockConstructorTestingTNewRecipeService_) *RecipeService_ {
	mock := &RecipeService_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
