// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// StepDelivery_ is an autogenerated mock type for the StepDelivery_ type
type StepDelivery_ struct {
	mock.Mock
}

// DeleteStepById provides a mock function with given fields: e
func (_m *StepDelivery_) DeleteStepById(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteStepByRecipeId provides a mock function with given fields: e
func (_m *StepDelivery_) DeleteStepByRecipeId(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertStep provides a mock function with given fields: e
func (_m *StepDelivery_) InsertStep(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStepById provides a mock function with given fields: e
func (_m *StepDelivery_) UpdateStepById(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewStepDelivery_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewStepDelivery_ creates a new instance of StepDelivery_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStepDelivery_(t mockConstructorTestingTNewStepDelivery_) *StepDelivery_ {
	mock := &StepDelivery_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
