// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	transaction_details "alta-cookit-be/features/transaction_details"

	mock "github.com/stretchr/testify/mock"
)

// TransactionDetailData_ is an autogenerated mock type for the TransactionDetailData_ type
type TransactionDetailData_ struct {
	mock.Mock
}

// ActionValidator provides a mock function with given fields: id, loggedInUserId
func (_m *TransactionDetailData_) ActionValidator(id uint, loggedInUserId uint) bool {
	ret := _m.Called(id, loggedInUserId)

	var r0 bool
	if rf, ok := ret.Get(0).(func(uint, uint) bool); ok {
		r0 = rf(id, loggedInUserId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SelectTransactionDetailById provides a mock function with given fields: transactionEntity
func (_m *TransactionDetailData_) SelectTransactionDetailById(transactionEntity *transaction_details.TransactionDetailEntity) (*transaction_details.TransactionDetailEntity, error) {
	ret := _m.Called(transactionEntity)

	var r0 *transaction_details.TransactionDetailEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*transaction_details.TransactionDetailEntity) (*transaction_details.TransactionDetailEntity, error)); ok {
		return rf(transactionEntity)
	}
	if rf, ok := ret.Get(0).(func(*transaction_details.TransactionDetailEntity) *transaction_details.TransactionDetailEntity); ok {
		r0 = rf(transactionEntity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction_details.TransactionDetailEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*transaction_details.TransactionDetailEntity) error); ok {
		r1 = rf(transactionEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTransactionDetailData_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionDetailData_ creates a new instance of TransactionDetailData_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionDetailData_(t mockConstructorTestingTNewTransactionDetailData_) *TransactionDetailData_ {
	mock := &TransactionDetailData_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
