// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// TransactionDetailDelivery_ is an autogenerated mock type for the TransactionDetailDelivery_ type
type TransactionDetailDelivery_ struct {
	mock.Mock
}

// SelectTransactionDetailById provides a mock function with given fields: e
func (_m *TransactionDetailDelivery_) SelectTransactionDetailById(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTransactionDetailDelivery_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionDetailDelivery_ creates a new instance of TransactionDetailDelivery_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionDetailDelivery_(t mockConstructorTestingTNewTransactionDetailDelivery_) *TransactionDetailDelivery_ {
	mock := &TransactionDetailDelivery_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
