// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// TransactionDelivery_ is an autogenerated mock type for the TransactionDelivery_ type
type TransactionDelivery_ struct {
	mock.Mock
}

// InsertTransaction provides a mock function with given fields: e
func (_m *TransactionDelivery_) InsertTransaction(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectTransactionsByUserId provides a mock function with given fields: e
func (_m *TransactionDelivery_) SelectTransactionsByUserId(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransactionStatusById provides a mock function with given fields: e
func (_m *TransactionDelivery_) UpdateTransactionStatusById(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransactionStatusByMidtrans provides a mock function with given fields: e
func (_m *TransactionDelivery_) UpdateTransactionStatusByMidtrans(e echo.Context) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTransactionDelivery_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionDelivery_ creates a new instance of TransactionDelivery_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionDelivery_(t mockConstructorTestingTNewTransactionDelivery_) *TransactionDelivery_ {
	mock := &TransactionDelivery_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
