// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	models "alta-cookit-be/features/transactions/models"

	mock "github.com/stretchr/testify/mock"

	transactions "alta-cookit-be/features/transactions"
)

// TransactionData_ is an autogenerated mock type for the TransactionData_ type
type TransactionData_ struct {
	mock.Mock
}

// ActionValidator provides a mock function with given fields: id, customerUserId
func (_m *TransactionData_) ActionValidator(id uint, customerUserId uint) bool {
	ret := _m.Called(id, customerUserId)

	var r0 bool
	if rf, ok := ret.Get(0).(func(uint, uint) bool); ok {
		r0 = rf(id, customerUserId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// InsertTransaction provides a mock function with given fields: transactionEntity
func (_m *TransactionData_) InsertTransaction(transactionEntity *transactions.TransactionEntity) (*transactions.TransactionEntity, error) {
	ret := _m.Called(transactionEntity)

	var r0 *transactions.TransactionEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*transactions.TransactionEntity) (*transactions.TransactionEntity, error)); ok {
		return rf(transactionEntity)
	}
	if rf, ok := ret.Get(0).(func(*transactions.TransactionEntity) *transactions.TransactionEntity); ok {
		r0 = rf(transactionEntity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transactions.TransactionEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*transactions.TransactionEntity) error); ok {
		r1 = rf(transactionEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectTransactionById provides a mock function with given fields: id
func (_m *TransactionData_) SelectTransactionById(id uint) *models.Transaction {
	ret := _m.Called(id)

	var r0 *models.Transaction
	if rf, ok := ret.Get(0).(func(uint) *models.Transaction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	return r0
}

// SelectTransactionByTransactionDetailId provides a mock function with given fields: transactionDetailId
func (_m *TransactionData_) SelectTransactionByTransactionDetailId(transactionDetailId uint) *models.Transaction {
	ret := _m.Called(transactionDetailId)

	var r0 *models.Transaction
	if rf, ok := ret.Get(0).(func(uint) *models.Transaction); ok {
		r0 = rf(transactionDetailId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	return r0
}

// SelectTransactionsByUserId provides a mock function with given fields: transactionEntity
func (_m *TransactionData_) SelectTransactionsByUserId(transactionEntity *transactions.TransactionEntity) (*[]transactions.TransactionEntity, error) {
	ret := _m.Called(transactionEntity)

	var r0 *[]transactions.TransactionEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*transactions.TransactionEntity) (*[]transactions.TransactionEntity, error)); ok {
		return rf(transactionEntity)
	}
	if rf, ok := ret.Get(0).(func(*transactions.TransactionEntity) *[]transactions.TransactionEntity); ok {
		r0 = rf(transactionEntity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]transactions.TransactionEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*transactions.TransactionEntity) error); ok {
		r1 = rf(transactionEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTransactionStatusById provides a mock function with given fields: transactionEntity
func (_m *TransactionData_) UpdateTransactionStatusById(transactionEntity *transactions.TransactionEntity) error {
	ret := _m.Called(transactionEntity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*transactions.TransactionEntity) error); ok {
		r0 = rf(transactionEntity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTransactionStatusByMidtrans provides a mock function with given fields: transactionEntity
func (_m *TransactionData_) UpdateTransactionStatusByMidtrans(transactionEntity *transactions.TransactionEntity) error {
	ret := _m.Called(transactionEntity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*transactions.TransactionEntity) error); ok {
		r0 = rf(transactionEntity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTransactionData_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionData_ creates a new instance of TransactionData_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionData_(t mockConstructorTestingTNewTransactionData_) *TransactionData_ {
	mock := &TransactionData_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
